---
# tasks/change_timezone.yml (ubuntu_common)
# Prefix : uc
# タイムゾーンを変更する.

- name: Symlink localtime from zoneinfo
  file:
    src: "/usr/share/zoneinfo/{{ system_time_zone | default(uc_default_system_timezone) }}"
    dest: /etc/localtime
    state: link
    owner: root
    group: root
  notify:
    - update timezone

- name: Set time zone
  copy:
    content: "{{ system_time_zone | default(uc_default_system_timezone) }}\n"
    dest: /etc/timezone
    owner: root
    group: root
    mode: "0644"
    backup: yes
  notify:
    - update timezone
